name: aquaculture
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mqtt_client: ^9.6.1
  provider: ^6.1.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  email_validator: ^3.0.0
  sign_in_button: ^4.0.1
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^19.4.0
  syncfusion_flutter_gauges: ^30.2.4
  syncfusion_flutter_charts: ^30.2.5
  cloud_firestore: ^4.15.8
  image_picker: ^1.1.2
  firebase_storage: ^11.6.9
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.0.0
  syncfusion_flutter_core: ^30.2.5
  foundation: ^0.0.5
  flutter_native_splash: ^2.4.6
  rxdart: ^0.28.0
  path_provider: ^2.1.5
  device_info_plus: ^10.1.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#00FFFF"
  image: assets/splash_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/certs/emqxsl-ca.crt
    - assets/icon.png
